version: '3'
services:
  meguca:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - images:/meguca/images
    depends_on:
      - postgres
  postgres:
    build: docker/postgres
    shm_size: '256MB'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=meguca
      - POSTGRES_PASSWORD=meguca
      - POSTGRES_DB=meguca
volumes:
  images:
  db:
