[package]
name = "protocol"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.103", features = ["derive"]}
bincode = "1.2.0"
num-derive = "0.3.0"
num-traits = "0.2.10"
num = "0.2.0"
flate2 = "1.0.13"
serde-big-array = "0.2.0"
hex-buffer-serde = "0.2.0"
